### ISSUE TITLE
请问starman config应该如何重新配置

### ISSUE THREAD

**Issue by zhbink** [dongli/starman#1]
我似乎是starman config配置错误，以后再使用一切操作都显示:
```
/usr/share/ruby/psych.rb:248:in `parse': (<unknown>): mapping values are not allowed in this context at line 9 column 16 (Psych::SyntaxError)
        from /usr/share/ruby/psych.rb:248:in `parse_stream'
        from /usr/share/ruby/psych.rb:196:in `parse'
        from /usr/share/ruby/psych.rb:123:in `load'
        from /home/starman/framework/settings.rb:90:in `init'
        from /home/starman/framework/commands/command_parser.rb:44:in `parse_packages'
        from /home/starman/framework/commands/uninstall.rb:16:in `initialize'
        from /home/starman/starman:41:in `new'
        from /home/starman/starman:41:in `<main>'
```
请问该如何进入config并重新配置这个文件呢？感谢🙏

**Comment by dongli** [comment]
你可以运行starman config命令吗？配置文件一般在/var/starman/conf.yml或者$HOME/.starman/conf.yml。

**Comment by zhbink** [comment]
第一次是可以运行starman config的，被我配置完之后就不行了
我没有找到/var/starman/conf.ym和$HOME/.starman/conf.yml。。
我可以通过什么指令重新安装starman吗？

**Comment by dongli** [comment]
你可以试试重新运行starman setup命令，加上`-f`选项，即强制重新配置。

**Comment by zhbink** [comment]
之前就是-f的，因为提示没有gcc...
```
[root@iZ2ze1onpk09a3mhfto815Z var]# starman setup --install-root /home/software --rc-root /home/confandfiles/ --cache-root /home/packages/ -f
[Warning]: There are no GCC compilers. Install ones or use your preferred ones, and run again with -f option!
```
可是我应该是已经安装gcc了
```
[root@iZ2ze1onpk09a3mhfto815Z var]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
```

再次运行setup
```
[root@iZ2ze1onpk09a3mhfto815Z var]# starman setup --install-root /home/software --rc-root /home/confandfiles/ --cache-root /home/packages/ 
[Error]: STARMAN has been set already!
```

**Comment by dongli** [comment]
请检查一下有没有`g++`，一般也是需要C++编译器的，如果需要用Fortran，还需要`gfortran`。

**Comment by zhbink** [comment]
装了gfortran，重新使用`starman setup ... -f`可以使用`starman config`了
我在想是不是我上一次`starman setup ... -f`就已经可以了呢。。
感谢！

**Comment by dongli** [comment]
只要系统有`gcc`和`g++`就可以了，如果没有，先装上，然后重新运行`setup`命令，加上`-f`选项。

**Comment by zhbink** [comment]
嗯嗯 对的
