### ISSUE TITLE
curl: (23) Failed writing body (0 != 1448)

### ISSUE THREAD

**Issue by maxiaojun123** [dongli/starman#9]
when I use : starman install xxx, it shows:
/home/shenhf/majun/starman/framework/system/os/mac.rb:5: warning: Insecure world writable dir /home/shenhf in PATH, mode 040707
[Notice]: Downloading package libiconv.
                                                                           0.0%Warning: Failed to create the file /opt/starman/packages/libiconv-1.14.tar.gz
                                                                           0.0%
curl: (23) Failed writing body (0 != 1448)
[Error]: Failed to download http://ftpmirror.gnu.org/libiconv/libiconv-1.14.tar.gz!

how to fix it out?

**Comment by dongli** [comment]
It seems you do not have write permission in /opt, please check it first.

**Comment by maxiaojun123** [comment]
It's my pleasure that you can reply. Thanks a lot. When I switch $root,it could work ,but another problem occurs:

[root@centos6 starman]# starman install libpng
/home/shenhf/majun/starman/framework/system/os/mac.rb:5: warning: Insecure world writable dir /home/shenhf in PATH, mode 040707
[Notice]: Install package libiconv.
[Notice]: Apply patch #0 to libiconv.
patching file srclib/stdio.in.h
==> ./configure --prefix=/opt/starman/software/libiconv/1.14/7049cc0af5b117
==> make 
==> make install
[Notice]: Downloading package zlib.
curl: (35) SSL connect error
[Error]: Failed to download https://github.com/madler/zlib/archive/v1.2.8.tar.gz!
[root@centos6 starman]# starman update
/home/shenhf/majun/starman/framework/system/os/mac.rb:5: warning: Insecure world writable dir /home/shenhf in PATH, mode 040707
[Error]: Sorry, you haven't installed STARMAN using git!
I have installed zlib1.2.11, I even don't konw whether the starman is completed installed or not.

**Comment by maxiaojun123** [comment]
thanks a lot, this problem has been solved . I wanna ask that can the software which was installed by starman support cesm2 or clm5.0???

**Comment by wanghai860115** [comment]
董老师好！
我第一次使用的starman配置用的gfortran，昨天想用pgf90来安装netcdf，然后就贸然修改了conf.yml。结果，现在总报错，即使我改回到原来的conf.yml也还是出现下面的错误：
Traceback (most recent call last):
	8: from ./starman:42:in `<main>'
	7: from ./starman:42:in `new'
	6: from /home/tqybk/wanghai/starman/framework/commands/install.rb:27:in `initialize'
	5: from /home/tqybk/wanghai/starman/framework/commands/command_parser.rb:44:in `parse_packages'
	4: from /home/tqybk/wanghai/starman/framework/settings.rb:90:in `init'
	3: from /usr/lib/ruby/2.5.0/psych.rb:263:in `load'
	2: from /usr/lib/ruby/2.5.0/psych.rb:350:in `parse'
	1: from /usr/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
/usr/lib/ruby/2.5.0/psych.rb:402:in `parse': (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 10 column 14 (Psych::SyntaxError)
请问董老师怎么修复？如果我想改conf.yml用pgf90编译fortran 部分，又该怎么办？叩谢！

**Comment by daye222** [comment]
董老师好
       ifort的路径不在/usr/bin/, 在/opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/这个路径下；
       所以我将这个路径添加在了conf.yml 里面（如下所示），但是最后安装的netcdf只有netcdf@4.7.2 netcdf-c@4.7.2 netcdf-fortran@4.5.2；ifort版的netcdf并没有安装。
       这种情况，我该怎么办呢？

“defaults:
compiler_set: gcc_8.3.1
compiler_sets:
    gcc_8.3.1:
    c: "/usr/bin/gcc"
    cxx: "/usr/bin/g++"
    fortran: "/usr/bin/gfortran"
    ifortran: "/opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/ifort"
”
